In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [2]:
scale_record = pd.read_csv("Spare-it V5 scale records Jan 1 to Oct 16 2023-001.csv")

In [3]:
scale_record.head()

,createdat,iotid,hide,bin,errorcode,weight,battery,updatedat,weightdiff,year,month,day
0,2023-01-02 12:41:00.000,lora-000060,False,95171614-b019-4eb9-b726-0af6674a9451,NO_ERROR,14100.862135,2596.017395,2023-01-02 12:41:00.000,NaN,2023,1,2
1,2023-01-02 13:02:00.000,lora-000060,False,95171614-b019-4eb9-b726-0af6674a9451,NO_ERROR,14100.862135,2595.101854,2023-01-02 13:02:00.000,NaN,2023,1,2
2,2023-01-02 13:53:00.000,lora-000060,False,95171614-b019-4eb9-b726-0af6674a9451,NO_ERROR,14100.862135,2596.169986,2023-01-02 13:53:00.000,NaN,2023,1,2
3,2023-01-02 16:30:00.000,lora-000060,False,95171614-b019-4eb9-b726-0af6674a9451,NO_ERROR,14100.862135,2595.559625,2023-01-02 16:30:00.000,NaN,2023,1,2
4,2023-01-02 16:39:00.000,lora-000060,False,95171614-b019-4eb9-b726-0af6674a9451,NO_ERROR,14100.862135,2594.186313,2023-01-02 16:39:00.000,NaN,2023,1,2

The featues of dataset

In [8]:
createdat_count = np.unique(scale_record.createdat, return_counts=True)

In [13]:
list(createdat_count[1])
# a different number of records for each createdat

[24,
 24,
 14,
 20,
 18,
 18,
 22,
 16,
 18,
 24,
 36,
 22,
 26,
 26,
 36,
 30,
 16,
 28,
 26,
 22,
 22,
 22,
 30,
 26,
 46,
 16,
 14,
 22,
 16,
 22,
 26,
 24,
 14,
 14,
 20,
 22,
 22,
 16,
 14,
 26,
 34,
 22,
 28,
 26,
 34,
 32,
 14,
 28,
 26,
 22,
 22,
 24,
 32,
 24,
 44,
 16,
 14,
 18,
 20,
 20,
 28,
 24,
 14,
 12,
 22,
 20,
 24,
 16,
 16,
 20,
 28,
 28,
 30,
 24,
 34,
 32,
 16,
 28,
 26,
 22,
 20,
 26,
 32,
 24,
 46,
 12,
 14,
 20,
 16,
 22,
 30,
 24,
 12,
 12,
 24,
 20,
 22,
 22,
 18,
 16,
 34,
 28,
 26,
 24,
 38,
 30,
 18,
 28,
 24,
 20,
 20,
 26,
 32,
 28,
 38,
 16,
 16,
 18,
 14,
 20,
 32,
 22,
 14,
 12,
 22,
 20,
 20,
 24,
 18,
 20,
 32,
 32,
 24,
 26,
 34,
 30,
 20,
 24,
 26,
 16,
 24,
 24,
 30,
 26,
 38,
 22,
 20,
 16,
 18,
 16,
 30,
 20,
 18,
 10,
 26,
 22,
 16,
 26,
 16,
 22,
 32,
 34,
 22,
 28,
 36,
 26,
 20,
 24,
 26,
 16,
 26,
 24,
 30,
 26,
 36,
 22,
 22,
 18,
 18,
 16,
 30,
 18,
 18,
 10,
 26,
 22,
 18,
 26,
 16,
 22,
 30,
 34,
 22,
 32,
 34,
 28,
 20,
 24,
 22,
 20,
 26,
 24,
 32,
 24,
 34,
 24,
 20,
 18,
 18,
 18,
 28,
 20,
 22,
 8,
 24,
 18,
 16,
 28,
 18,
 18,
 30,
 34,
 22,
 32,
 32,
 28,
 22,
 26,
 20,
 20,
 24,
 22,
 30,
 24,
 32,
 32,
 20,
 18,
 16,
 14,
 32,
 18,
 22,
 12,
 22,
 14,
 18,
 28,
 16,
 20,
 28,
 36,
 22,
 32,
 28,
 28,
 28,
 18,
 24,
 24,
 24,
 22,
 30,
 26,
 22,
 40,
 18,
 20,
 18,
 16,
 26,
 20,
 24,
 10,
 18,
 14,
 18,
 20,
 18,
 16,
 26,
 36,
 22,
 30,
 26,
 30,
 26,
 16,
 24,
 22,
 22,
 24,
 30,
 24,
 26,
 40,
 16,
 24,
 16,
 14,
 28,
 20,
 24,
 12,
 18,
 12,
 22,
 22,
 22,
 18,
 28,
 40,
 22,
 30,
 28,
 28,
 26,
 18,
 24,
 24,
 20,
 24,
 32,
 22,
 26,
 40,
 18,
 20,
 18,
 18,
 26,
 14,
 28,
 12,
 18,
 14,
 20,
 24,
 24,
 16,
 28,
 40,
 20,
 30,
 26,
 36,
 20,
 20,
 24,
 24,
 20,
 28,
 30,
 26,
 24,
 40,
 18,
 22,
 18,
 18,
 24,
 18,
 28,
 10,
 16,
 16,
 20,
 26,
 20,
 14,
 28,
 38,
 24,
 26,
 28,
 36,
 26,
 18,
 18,
 22,
 18,
 24,
 28,
 34,
 22,
 40,
 18,
 20,
 18,
 20,
 22,
 22,
 28,
 12,
 14,
 16,
 18,
 26,
 18,
 18,
 28,
 34,
 28,
 22,
 28,
 36,
 28,
 20,
 24,
 26,
 20,
 22,
 28,
 32,
 24,
 42,
 16,
 22,
 16,
 20,
 22,
 22,
 28,
 12,
 16,
 20,
 16,
 26,
 16,
 18,
 26,
 34,
 30,
 24,
 26,
 36,
 26,
 22,
 24,
 26,
 22,
 24,
 26,
 30,
 24,
 42,
 14,
 26,
 16,
 20,
 22,
 22,
 24,
 16,
 16,
 20,
 18,
 22,
 18,
 18,
 22,
 36,
 30,
 26,
 24,
 36,
 26,
 18,
 28,
 26,
 22,
 24,
 24,
 32,
 24,
 40,
 12,
 24,
 14,
 20,
 14,
 26,
 24,
 16,
 16,
 20,
 20,
 18,
 22,
 22,
 22,
 28,
 30,
 26,
 26,
 36,
 30,
 16,
 28,
 22,
 22,
 22,
 22,
 30,
 24,
 44,
 16,
 18,
 18,
 20,
 16,
 30,
 24,
 16,
 10,
 24,
 18,
 20,
 24,
 20,
 24,
 30,
 30,
 26,
 26,
 34,
 32,
 18,
 28,
 18,
 22,
 22,
 22,
 30,
 24,
 44,
 16,
 18,
 20,
 16,
 16,
 30,
 22,
 18,
 10,
 20,
 18,
 20,
 24,
 20,
 24,
 30,
 26,
 32,
 26,
 32,
 30,
 18,
 30,
 20,
 22,
 20,
 20,
 32,
 24,
 42,
 20,
 14,
 24,
 16,
 16,
 28,
 20,
 18,
 12,
 20,
 20,
 16,
 26,
 22,
 24,
 28,
 28,
 32,
 28,
 34,
 28,
 14,
 30,
 22,
 20,
 22,
 22,
 28,
 28,
 32,
 26,
 14,
 26,
 16,
 16,
 32,
 16,
 18,
 12,
 18,
 18,
 20,
 26,
 16,
 18,
 30,
 30,
 28,
 30,
 32,
 26,
 22,
 24,
 26,
 20,
 24,
 24,
 28,
 28,
 28,
 34,
 12,
 28,
 16,
 16,
 24,
 20,
 24,
 12,
 16,
 18,
 18,
 26,
 18,
 14,
 32,
 30,
 26,
 32,
 30,
 22,
 24,
 24,
 28,
 20,
 24,
 24,
 28,
 30,
 28,
 34,
 12,
 28,
 16,
 18,
 22,
 18,
 26,
 12,
 18,
 18,
 18,
 24,
 20,
 16,
 26,
 30,
 22,
 28,
 28,
 24,
 22,
 22,
 26,
 22,
 24,
 22,
 30,
 30,
 30,
 34,
 8,
 26,
 16,
 20,
 22,
 20,
 26,
 10,
 18,
 16,
 16,
 30,
 18,
 16,
 28,
 32,
 18,
 34,
 26,
 28,
 26,
 24,
 22,
 22,
 24,
 22,
 30,
 30,
 28,
 42,
 8,
 24,
 16,
 18,
 22,
 20,
 28,
 10,
 18,
 14,
 16,
 26,
 24,
 16,
 26,
 36,
 22,
 28,
 24,
 32,
 30,
 18,
 24,
 26,
 22,
 16,
 30,
 32,
 24,
 46,
 10,
 22,
 18,
 18,
 20,
 20,
 28,
 8,
 22,
 18,
 14,
 24,
 24,
 18,
 28,
 36,
 22,
 28,
 26,
 34,
 28,
 14,
 28,
 24,
 24,
 18,
 28,
 28,
 26,
 46,
 12,
 22,
 18,
 18,
 22,
 20,
 24,
 12,
 22,
 16,
 16,
 26,
 22,
 16,
 28,
 34,
 24,
 30,
 22,
 36,
 24,
 14,
 26,
 24,
 20,
 20,
 28,
 30,
 26,
 44,
 12,
 20,
 22,
 14,
 24,
 20,
 22,
 14,
 20,
 12,
 20,
 20,
 28,
 16,
 28,
 34,
 24,
 30,
 24,
 36,
 26,
 14,
 32,
 26,
 18,
 20,
 26,
 30,
 24,
 48,
 12,
 18,
 22,
 16,
 20,
 26,
 22,
 16,
 18,
 18,
 18,
 20,
 22,
 18,
 26,
 30,
 28,
 26,
 26,
 36,
 30,
 12,
 30,
 22,
 24,
 24,
 20,
 30,
 24,
 48,
 16,
 16,
 26,
 16,
 22,
 24,
 24,
 16,
 12,
 24,
 20,
 20,
 18,
 16,
 28,
 26,
 30,
 28,
 26,
 34,
 28,
 16,
 30,
 20,
 24,
 24,
 22,
 32,
 22,
 48,
 16,
 12,
 26,
 18,
 22,
 22,
 24,
 18,
 10,
 24,
 20,
 20,
 18,
 20,
 22,
 28,
 28,
 28,
 30,
 36,
 26,
 14,
 30,
 18,
 28,
 22,
 20,
 32,
 26,
 50,
 16,
 12,
 24,
 18,
 24,
 20,
 26,
 14,
 10,
 26,
 20,
 14,
 18,
 22,
 24,
 28,
 28,
 22,
 30,
 38,
 24,
 16,
 28,
 16,
 26,
 22,
 20,
 28,
 30,
 44,
 22,
 14,
 24,
 16,
 20,
 26,
 26,
 14,
 12,
 20,
 22,
 14,
 22,
 22,
 22,
 30,
 28,
 22,
 30,
 32,
 22,
 24,
 26,
 20,
 20,
 26,
 22,
 30,
 30,
 42,
 26,
 14,
 22,
 18,
 16,
 24,
 26,
 18,
 12,
 22,
 20,
 14,
 26,
 ...]

In [32]:
sample_number = scale_record.shape[0]
sample_number

26979124

Whether some columns or rows can be deleted?

In [36]:
cols = ['iotid','bin']
scale_record.groupby(cols).size()
# the number of records for each bin is different
# iotid and bin do not have a one-to-one correspondence. Q:why?

iotid        bin
lora-000014  65fdffd5-af50-4157-adfa-582251a1b27d    19136
lora-000015  4f56d445-de55-4578-86bc-9a61bceb2c7a    21459
lora-000017  d08c0976-ceb0-4bf3-8d54-23e21eb5e28a    19087
lora-000051  e8324a97-0523-44aa-a4a4-3e9aae344d24    44400
lora-000052  9513caf9-ea3a-4486-8e94-59ce2094c73c    21360
                                                     ...
lora-001802  bca1fba1-5d12-484d-a1e6-fe8cad3027ab     1143
lora-001803  12a5e0fa-e9f2-4978-aba8-757f66ae5e5a     5416
lora-001815  2cfd5943-277e-4d6f-a172-c304d990c2d8     1130
             f0812a21-ab64-4f8e-9cda-3b7bd81b0dc5    12052
lora-001825  e9d32794-2a58-4321-8acd-1788b9ed704e      541
Length: 1326, dtype: int64

In [35]:
createdat_ifequal_updatedat = [(scale_record.createdat[i] == scale_record.updatedat[i]) for i in range(sample_number)]
np.unique(createdat_ifequal_updatedat, return_counts=True)
#createdat and updatedat do not have a one-to-one correspondence
#Q: In which case is createdat different from updatedat? The reasons?

(array([False,  True]), array([   19973, 26959151], dtype=int64))

In [34]:
np.unique(scale_record.hide, return_counts=True)

(array([False,  True]), array([26765177,   213947], dtype=int64))

My plan

1.Explore more data through plotting.
2.Find all anomalies and categorize them and infer causes.